spring:
  profiles:
    active: dev
---
server:
  port: 8201
spring:
  profiles: dev #开发环境
  application:
    name: reader-cloud-config

eureka:
  client:
    service-url:
      defaultZone: eureka-server-7001:7001/eureka
---
server:
  port: 8202
spring:
  profiles: test #开发环境
  application:
    name: reader-cloud-config

eureka:
  client:
    service-url:
      defaultZone: eureka-server-7001:7001/eureka